services:
  - type: web
    name: my-web-service
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    environment:
      pythonVersion: 3.10.13
